name: retip
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - pandas
  - openpyxl
  - scikit-learn
  - xgboost
  - jupyterlab
  - rdkit
  - mordred=1.2.0
  - pubchempy
  - tqdm
  - pip
  - pip:
    - autogluon==0.1.0
    - mxnet<2.0.0
