name: retip
channels:
  - conda-forge
dependencies:
  - python=3.10
  - mordredcommunity
  - tqdm
  - selenium
  - geckodriver
  - pip
  - pip:
    - autogluon==0.8.2
    - numpy
    - scipy
    - pandas
    - openpyxl
    - scikit-learn
    - xgboost
    - joblib
    - jupyter
    - pubchempy
    - bokeh
    - tqdm
