name: retip
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - scipy
  - pandas
  - openpyxl
  - scikit-learn
  - xgboost
  - joblib
  - jupyterlab
  - mordred=1.2.0
  - pubchempy
  - tqdm
  - bokeh
  - selenium
  - geckodriver
  - pip
  - pip:
    - autogluon==0.5.2
